wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: huggingface
    huggingface_version: 4.19.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.3
    start_time: 1666584974.475958
    t:
      1:
      - 1
      - 3
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      2:
      - 1
      - 3
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      3:
      - 23
      4: 3.8.3
      5: 0.13.4
      6: 4.19.0
      8:
      - 5
