wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.3
    start_time: 1753163216.247294
    t:
      1:
      - 1
      - 5
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 49
      - 51
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.8.3
      5: 0.13.4
      8:
      - 1
      - 5
criterion:
  desc: null
  value: gini
min_samples_leaf:
  desc: null
  value: 10
min_samples_split:
  desc: null
  value: 10
n_estimators:
  desc: null
  value: 50
